spring.application.name=SmartRestaurantEngine

# SQL Database configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/your_sql_db
#spring.datasource.username=root
#spring.datasource.password=yourpassword
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
server.port=4000

# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/restaurant_2.products

jwt.secret=MyVeryStrongJwtSecretKeyThatIsAtLeast32Chars
jwt.expirationMs=900000
